### ISSUE TITLE
Should be removed

### ISSUE THREAD

**Issue by HHGAG** [goceevo/hhg-multistore-CE-plugin#1]
https://github.com/goceevo/hhg-multistore-CE-plugin/blob/dbc7efb95f468fbc7ce5fc7bbf8e8361541b24c5/core/modules/ceevo_globals.php#L2

**Comment by HHGAG** [comment]
These also:
https://github.com/goceevo/hhg-multistore-CE-plugin/blob/dbc7efb95f468fbc7ce5fc7bbf8e8361541b24c5/core/modules/checkout_ceevo_popup.php#L68

**Comment by danielpun** [comment]
fixed
