### ISSUE TITLE
A new theme instance should be used per module

### ISSUE THREAD

**Issue by HHGAG** [goceevo/hhg-multistore-CE-plugin#2]
A new theme instance should be user per module
`$module_theme = new hhg_theme;`
All further assignments should be mapped to the new instance 
https://github.com/goceevo/hhg-multistore-CE-plugin/blob/dbc7efb95f468fbc7ce5fc7bbf8e8361541b24c5/core/modules/checkout_ceevo_popup.php#L47
only this assignment should stay
https://github.com/goceevo/hhg-multistore-CE-plugin/blob/dbc7efb95f468fbc7ce5fc7bbf8e8361541b24c5/core/modules/checkout_ceevo_popup.php#L61

**Comment by danielpun** [comment]
fixed
