### ISSUE TITLE
Empty cart with reset method

### ISSUE THREAD

**Issue by HHGAG** [goceevo/hhg-multistore-CE-plugin#3]
See

> core/modules/checkout_process.php#L548
`$registry['cart']->reset(true, $store_id);`

https://github.com/goceevo/hhg-multistore-CE-plugin/blob/dbc7efb95f468fbc7ce5fc7bbf8e8361541b24c5/core/modules/ceevo_globals.php#L13

**Comment by danielpun** [comment]
fixed
