### ISSUE TITLE
Undefined constants in ceevo_payment.php

### ISSUE THREAD

**Issue by tuxedo-rb** [goceevo/hhg-multistore-CE-plugin#5]
Hello, thanks for the plugin code.

We tested/analysed the plugin and found two undefined constants.
One of them may lead to a SQL-error.

`MODULE_PAYMENT_CEEVO_PAYMENT_ZONE` is a undefined constant, so the code inside of the if-block is dead code.
[https://github.com/goceevo/hhg-multistore-CE-plugin/blob/dd213c27dc6804096ac6596ffec8c58c480dcac6/core/plugins/payment/ceevo_payment.php#L30](https://github.com/goceevo/hhg-multistore-CE-plugin/blob/dd213c27dc6804096ac6596ffec8c58c480dcac6/core/plugins/payment/ceevo_payment.php#L30)

The SQL-query two lines further would throw a SQL-error when the payment plugin 'ipayment' is not installed (which is the case in our company).
In this case `MODULE_PAYMENT_IPAYMENT_ZONE` is also a undefined constant.
[https://github.com/goceevo/hhg-multistore-CE-plugin/blob/dd213c27dc6804096ac6596ffec8c58c480dcac6/core/plugins/payment/ceevo_payment.php#L32](https://github.com/goceevo/hhg-multistore-CE-plugin/blob/dd213c27dc6804096ac6596ffec8c58c480dcac6/core/plugins/payment/ceevo_payment.php#L32)

**Comment by danielpun** [comment]
Thanks a lot. Fixed now
